---
- block:
    - yum:
        update_cache: true
        name: epel-release
        state: present

    - selinux:
        state: permissive
        policy: targeted

    - hostname:
        name: "{{ inventory_hostname }}"
  become: true
